# Generated by Django 5.0.2 on 2024-02-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_publication_date_book_publication_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
